### ISSUE TITLE
FARALLONES - 355 in wrong location

### ISSUE THREAD

**Issue by kwilcox** [USGS-CMG/usgs-cmg-portal#120]
@emontgomery-usgs  Datafiles [here](http://geoport.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/Data/FARALLONES/catalog.html) report (-120.933334, 37.783833), but that seems to be in the middle of California!

**Comment by emontgomery-usgs** [comment]
@kwilcox - that one is correct on stellwagen but didn't get updated on geoport.  I will make sure it's there, but if you want to do a quick fix at the end instead of waiting for the next re-run, the lon should be -122.933...

**Comment by emontgomery-usgs** [comment]
@rsignell-usgs, these files  (and those MBAY_WEST, and  ECOHAB_I (tickets 121 and 122)) are on geoport ready to be converted to CF-1.6 again.  Did you update what's needed for me to be using the newest code?

**Comment by rsignell-usgs** [comment]
@emontgomery-usgs , I updated pyaxiom to 1.1.7 on geoport's conda environment, so if you do a git pull and then run you should be good to go.

**Comment by emontgomery-usgs** [comment]
@kwilcox this data is fixed and updated on CF-1.6: ready for you to re-harvest

**Comment by kwilcox** [comment]
@emontgomery-usgs I think you forgot one: http://geoport.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/Data/FARALLONES/3352.cdf.html

**Comment by emontgomery-usgs** [comment]
True, but the right thing is in CF-1.6, which I believe is where you
harvest from

 usgs/data2/emontgomery/stellwagen/CF-1.6/FARALLONES/3352-a.cdf;
---------------------------------------------
latitude, 38.78379821777344
longitude, -122.93329620361328


Back to you Kyle :>


On Tue, Feb 9, 2016 at 3:17 PM, Kyle Wilcox <notifications@github.com>
wrote:

> @emontgomery-usgs <https://github.com/emontgomery-usgs> I think you
> forgot one:
> http://geoport.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/Data/FARALLONES/3352.cdf.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/120#issuecomment-182044644>
> .
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356

**Comment by kwilcox** [comment]
latitude, 38.78379821777344
longitude, -122.93329620361328

Is still in the middle of California (although closer to water than the last point).  Is it incorrect again?

**Comment by rsignell-usgs** [comment]
Fun fact.  You can type "37.783833, -122.933334" into google search

**Comment by emontgomery-usgs** [comment]
that lat is wrong.  -122 is right.  Both are right here, so not sure what
went wrong. But will get both right shortly

Here's what I have, which shows 3351 & 2 in nominally the right place.
[image: Inline image 1]

On Tue, Feb 9, 2016 at 3:48 PM, Kyle Wilcox <notifications@github.com>
wrote:

> latitude, 38.78379821777344
> longitude, -122.93329620361328
>
> Is still in the middle of California (although closer to water than the
> last point). Is it incorrect again?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/120#issuecomment-182058008>
> .
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356

**Comment by rsignell-usgs** [comment]
@emontgomery-usgs, the lat is wrong here:
http://geoport.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/CF-1.6/FARALLONES/3352-a.cdf.ascii?latitude,longitude

**Comment by emontgomery-usgs** [comment]
New 335* with modified lat and lon are in CF-1.6.  Hope this solves it.

On Tue, Feb 9, 2016 at 3:56 PM, Rich Signell <notifications@github.com>
wrote:

> @emontgomery-usgs <https://github.com/emontgomery-usgs>, the lat is wrong
> here:
>
> http://geoport.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/CF-1.6/FARALLONES/3352-a.cdf.ascii?latitude,longitude
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/120#issuecomment-182064056>
> .
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356

**Comment by kwilcox** [comment]
![selection_102](https://cloud.githubusercontent.com/assets/13939/12930691/cca85b22-cf47-11e5-93bf-0b6ef5f79626.png)

There we go!

**Comment by emontgomery-usgs** [comment]
Thanks for the perseverance!

On Tue, Feb 9, 2016 at 4:11 PM, Kyle Wilcox <notifications@github.com>
wrote:

> [image: selection_102]
> <https://cloud.githubusercontent.com/assets/13939/12930691/cca85b22-cf47-11e5-93bf-0b6ef5f79626.png>
>
> There we go!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-CMG/usgs-cmg-portal/issues/120#issuecomment-182069372>
> .
>



-- 
Ellyn Montgomery, Oceanographer and Data Manager
U.S. Geological Survey
Woods Hole Coastal and Marine Science Center
384 Woods Hole Rd., Woods Hole, MA, 02543-1598
(508) 457-2356
