### ISSUE TITLE
bindist and AGC_1202 not translated correctly in CF version

### ISSUE THREAD

**Issue by emontgomery-usgs** [USGS-CMG/usgs-cmg-portal#51]
For http://geoport.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/CF-1.6/HURRIRENE_BB/9141wh-a.nc.html, bindist is all 1e35, when the source file on stellwagen has data.

AGC_1202 is a bit stranger-  If you open it in toolsUI, the AGC_1202 variable lists the data as all NaN, but as the attached shows, there's reasonable data in the file.
![missing_agc](https://cloud.githubusercontent.com/assets/1771422/6988364/a2bee232-da1e-11e4-98a1-78f3499f1bee.png)

**Comment by rsignell-usgs** [comment]
@emontgomery-usgs , yes, it looks like bindist didn't get converted correctly by the python script:

Input:
http://geoport.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/Data/HURRIRENE_BB/9141wh-a.nc.ascii?bindist[0:1:32]
```
Dataset {
    Float32 bindist[depth = 33];
} usgs/data2/emontgomery/stellwagen/Data/HURRIRENE_BB/9141wh-a.nc;
---------------------------------------------
bindist[33]
1.62, 2.12, 2.62, 3.12, 3.62, 4.12, 4.62, 5.12, 5.62, 6.12, 6.62, 7.12, 7.62, 8.12, 8.62, 9.12, 9.62, 10.12, 10.62, 11.12, 11.62, 12.12, 12.62, 13.12, 13.62, 14.12, 14.62, 15.12, 15.62, 16.12, 16.62, 17.12, 17.62
```

Output:
http://geoport.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/CF-1.6/HURRIRENE_BB/9141wh-a.nc.ascii?bindist[0:1:32]
```
Dataset {
    Float32 bindist[z = 33];
} usgs/data2/emontgomery/stellwagen/CF-1.6/HURRIRENE_BB/9141wh-a.nc;
---------------------------------------------
bindist[33]
1.0E35, 1.0E35, 1.0E35, 1.0E35, 1.0E35, 1.0E35, 1.0E35, 1.0E35, 1.0E35, 1.0E35, 1.0E35, 1.0E35, 1.0E35, 1.0E35, 1.0E35, 1.0E35, 1.0E35, 1.0E35, 1.0E35, 1.0E35, 1.0E35, 1.0E35, 1.0E35, 1.0E35, 1.0E35, 1.0E35, 1.0E35, 1.0E35, 1.0E35, 1.0E35, 1.0E35, 1.0E35, 1.0E35
```

**Comment by kwilcox** [comment]
@emontgomery-usgs @rsignell-usgs This is fixed in the codebase, the CF files will need to be regenerated (all of them, it was a bug effecting all variables with a single depth dimension)

**Comment by emontgomery-usgs** [comment]
@kwilcox - I re-ran data from HURRIRENE_BB as a test, and found some issues remain
the bad news:
bindist is still getting all NaN 
the u_1205, v_1206 and w_1204 variables are not in the output file - these were in the previous version- good thing I didn't overwrite!

The good news:
AGC_1202 looks like it should

**Comment by kwilcox** [comment]
@emontgomery-usgs I just ran the following command and can't reproduce the problems you are seeing.  Can you try it again after pulling the lastest code down?

```bash
python collect.py --download -p HURRIRENE_BB -f ./test_issue_51_download/ -o ./test_issue_51_output
```

I was able to verify that the C_51 variable was empty in the output file, but it is also empty in the original file: http://geoport.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/Data/HURRIRENE_BB/9143sc-a.nc.ascii?C_51[0:1:9794][0:1:0][0:1:0][0:1:0]

**Comment by emontgomery-usgs** [comment]
@rsignell-usgs You're right, there wasn't good conductivity in the original seacat file, so the 1e35 in the conductivity is correct.  Should the plotting program be smart enough to determine that 1e35 is FillVal, and shouldn't actually be plotted?

Pls check and see if the issues in the ADCP file affect the version you just generated.  Thnx!

**Comment by emontgomery-usgs** [comment]
@rsignell-usgs, I just pulled from upstream master and re-ran.  9141wh-a.nc  stlll has all NaN in bindist, and is missing, u_1205, V-1206, and W_1204.

**Comment by kwilcox** [comment]
Interesting...  here are my results.  I see data in bindist and see the u_1205, v_1206, and w_1204 variables: https://gist.github.com/kwilcox/042a76d27b5e2760d11d

**Comment by emontgomery-usgs** [comment]
I have used both ncdump and ncBrowse on the new file- neither sees any data in bindist.  
data:
```
$ ncdump -v bindist 9141wh-a.nc
<lots of output omitted>
 bindist = _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _,
    _, _, _, _, _, _, _, _, _, _, _ ;
}
```
If I do ncdump on U_1205, I get
```
$ ncdump -v u_1205 9141wh-a.nc
ncdump: u_1205: No such variable
```
Could ncdump not work well on netcdf4 files?  Or maybe I need other qualifiers.

With ncBrowse, the display looks generally correct, and I can display the attributes and plot variables like Tx_1211, but the variable list doesn't  include any of the 2-d vars.

**Comment by rsignell-usgs** [comment]
@kwilcox , I just cloned the latest https://github.com/USGS-CMG/usgs-cmg-portal and get the same empty bindist as @emontgomery-usgs.    
We must be using different versions of some requirement, right?

```
/test_issue_51_output/HURRIRENE_BB$ conda list 
requests                  2.6.0                    py27_0    defaults
epic2cf                   0.0.1                np19py27_0    ioos
thredds_crawler           1.0.0                    py27_0    ioos
pyaxiom                   0.0.8                np19py27_0    ioos

**Comment by rsignell-usgs** [comment]
@emontgomery-usgs , there was a bug in the convert.py script.   Can you try doing `git pull` and running 
```
python collect.py --download -p HURRIRENE_BB -f ./test_issue_51_download/ -o ./test_issue_51_output
ncdump -v bindist test_issue_51_output/HURRIRENE_BB/9141wh-a.nc
```

**Comment by emontgomery-usgs** [comment]
@rsignell-usgs "git pull" did not update collect.py, however, "git pull upstream master" did.

After updateing collect.py, I ran the commands you reqested and now there's non-nan data in bindist, and there's data in u_1205, v_1206 and w_1204.

Nice find!  I'm closing the ticket.

**Comment by emontgomery-usgs** [comment]
Here's why the Agc_1202 showed up as Nan in toolsUI-  it's valid_range attribute was set to 255-255 (not 0:255 or -255:255).  ToolsUI reads valid_range and discards data beyond the valid_range, ncBrowse doesn't, so it wasn't obvious that the attribute was wrong.
